### ISSUE TITLE
Allow Apple widget on Xen

### ISSUE THREAD

**Issue by Oxtie** [Matchstic/Xen-HTML#134]
I am using one Apple 🍎 widget but I hate to swipe it to left and it's placement 🤢

I would prefer XenHTML to load that widget and allow me to see it on home screen (empty area below or above icons) or in the lock screen (like any other Cydia widgets)

I didn't find any alternate solution to load standard Apple widgets on XenHTML etc

I'm on iOS 10.2

**Comment by Matchstic** [comment]
Loading Apple widgets is a much bigger task than it sounds, which is why I’ve not done it.

For example, I would need to:
- Reverse engineer how Apple widgets work on iOS 9, 10, 11 and 12 separately
- Figure out how to properly handle the “Show More” button on them
- Add support for them throughout Settings, including their own options
- Actually load and render the widgets

To me, that’s a huge undertaking, especially with the limited free time I have available.
