### ISSUE TITLE
Allow XenHTML to access local files

### ISSUE THREAD

**Issue by R2D2FISH** [Matchstic/Xen-HTML#56]
(I’m a total newbie to all of this so please keep that in mind when reading this lol)

XenHTML appears to be incapable of accessing local files.  This issue is particularly problematic when attempting to create widgets with 3D graphics, as many of these utilize standalone model files.  This appears to be a “feature” of WKWebView, which XenHTML uses.  In testing I’ve done, external files will load if they are loaded from an external server, but this is impractical for real use.

WKWebView will load files from an application’s “Tmp” folder, however.  Perhaps some file could be added to a widget which tells XenHTML which files to copy over to this folder, allowing the WKWebView to load the file.

Of course, an alternate solution would be to just run a local webserver, but that seems like an inefficient solution to me.

**Comment by Matchstic** [comment]
Hi,

This does sound like an issue of WKWebView that was fixed in iOS 9 and higher - the same restrictions applied for HTML files. As of right now, I’ve set any web view used to allow loading resources from / I.e. the entire file system.

Any chance I can work with an example of the issue via a widget please?

Cheers,
Matt

**Comment by R2D2FISH** [comment]
Sorry this was just me being stupid.  It works fine now.  Sorry to bother you.  (In case you were wondering I was messing around with the three.js examples and didn’t put certain files in the proper places)

Hope I didn’t waste too much of your time!
